export default [
  {
    menuName: "Virtual Terminal",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "POS",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Invoice Management",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Inventory Management	",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Sales",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "User Management",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Product Management",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Point Of Sale",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Customer Management",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Manage Invoice",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Create Invoice",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Recurring Invoice",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Invoice Settings",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Sales Summary",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Sales Trends",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Payment Methods",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Item Sales",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Category Sales",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Taxes",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Transaction Status",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "User Role",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
  {
    menuName: "Users",
    selectAll: false,
    add: false,
    edit: false,
    view: false,
    delete: false,
  },
];
