import { Circle, Codepen, Home, Inbox, Settings, Users } from "react-feather";

export default [
  {
    id: "merchant_dashboard-2",
    title: "Dashboard",
    icon: <Home size={12} />,
    navLink: "/merchant/payment-gateway",
    action: "merchant",
    resource: "Customer",
  },
  {
    id: "user-management",
    title: "User Managament",
    icon: <Settings size={12} />,
    navLink: "/user-management-setting",
    action: "merchant",
    resource: "Customer",
  },
  {
    id: "sales",
    title: "Sales",
    icon: <Home size={20} />,
    badge: "light-warning",
    badgeText: "7",
    children: [
      {
        id: "transaction-status",
        title: "Transaction Status",
        icon: <Circle size={12} />,
        navLink: "/merchant/transaction-status",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "taxes",
        title: "Taxes",
        icon: <Circle size={12} />,
        navLink: "/merchant/taxes",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "category-sales",
        title: "Category Sales",
        icon: <Circle size={12} />,
        navLink: "/merchant/category-sales",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "items-sales",
        title: "Items Sales",
        icon: <Circle size={12} />,
        navLink: "/merchant/items-sales",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "payment-method",
        title: "Payment Method",
        icon: <Circle size={12} />,
        navLink: "/merchant/payment-method",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "sales-trends",
        title: "Sales Trends",
        icon: <Circle size={12} />,
        navLink: "/merchant/sales-trends",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "sales-summary",
        title: "Sales Summary",
        icon: <Circle size={12} />,
        navLink: "/merchant/sales-summary",
        action: "merchant",
        resource: "Customer",
      },
    ],
  },
  {
    id: "invoice-Management",
    title: "Invoice Mangement",
    icon: <Users size={20} />,
    badge: "light-warning",
    children: [
      {
        id: "merchant-invoice-setting",
        title: "Invoice Setting",
        icon: <Circle size={12} />,
        navLink: "/merchant/invoice-setting",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "merchant-recurring-invoice",
        title: "Recurring Invoice",
        icon: <Circle size={12} />,
        navLink: "/merchant/recurring-invoice",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "merchant-create-invoice",
        title: "Create Invoice",
        icon: <Circle size={12} />,
        navLink: "/merchant/create-invoice",
        action: "merchant",
        resource: "Customer",
      },
    ],
  },
  {
    id: "inventry-management",
    title: "Inventry Management",
    icon: <Inbox size={12} />,
    navLink: "/merchant/inventry-management",
    action: "merchant",
    resource: "Customer",
  },
  {
    id: "p-o-s",
    title: "POS",
    icon: <Codepen size={12} />,
    badge: "light-warning",
    children: [
      {
        id: "customer-list",
        title: "Customer Management",
        icon: <Circle size={12} />,
        navLink: "/merchant/customer-list",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "point-of-sale",
        title: "Point Of Sale",
        icon: <Circle size={12} />,
        navLink: "/merchant/point-of-sale",
        action: "merchant",
        resource: "Customer",
      },
      {
        id: "product-managements",
        title: "Product Managements",
        icon: <Circle size={12} />,
        navLink: "/merchant/product-managment",
        action: "merchant",
        resource: "Customer",
      },
    ],
  },

  // {
  //   id: "virtual-terminal",
  //   title: "Virtual Terminal",
  //   icon: <Inbox size={12} />,
  //   navLink: "/merchant/virtual-terminal",
  //   action: "merchant",
  //   resource: "Customer",
  // },
];
